### ISSUE TITLE
corpus directory missing from repo?

### ISSUE THREAD

**Issue by dtjohnso** [lmullen/ats-corpus#1]
Perhaps I misunderstand the purpose of the repo vs. the zip on your website, but I expected from the README.md in the repo to see the 'corpus' directory here on github as well.

**Comment by lmullen** [comment]
Clarified in 25472bdd841ef4c4cb06bc854c0d95950c1d595f.

The corpus itself is available here: http://lincolnmullen.com/files/ats_corpus.zip

**Comment by dtjohnso** [comment]
Thanks for the clarification.
